server:
  port: 8080
spring:
  datasource:
    #数据库的配置
    url: jdbc:mysql://localhost:3306/hub?serverTimezone=Asia/Shanghai
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      #最大文件大小
      max-file-size: 10MB
      #最大请求文件大小
      max-request-size: 10MB
mybatis:
  #config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#项目保存根目录
basepath:
  basePath: '/Users/jiyu/Desktop/课程设计/projects'